"""Public API aliases for the foundational Phase 1 container models."""

from autofdtd.core.containers import (
    Scene,
    Simulation,
    Structure,
    StructurePrecedence,
    StructurePriorityMode,
)
from autofdtd.core.models import AutoFDTDModel, TaggedModel
from autofdtd.core.validation import AutoFDTDValidationWarning, UnsupportedFeatureError
from autofdtd.geometry import (
    Box,
    ClipOperation,
    Cylinder,
    GeometryArray,
    GeometryGroup,
    GeometryTransform,
    PolySlab,
    PrimitiveGeometry,
    Sphere,
    Transformed,
)
from autofdtd.grid import (
    AbstractSubpixelPolicy,
    AutoGrid,
    CustomGrid,
    CustomGridBoundaries,
    GridRefinement,
    GridSpec,
    LayerRefinementSpec,
    PolarizedAveraging,
    ResolvedGrid,
    ResolvedGridAxis,
    Staircasing,
    SubpixelSpec,
    UniformGrid,
)
from autofdtd.materials import (
    Debye,
    Drude,
    Lorentz,
    Medium,
    PECMedium,
    PMCMedium,
    PoleResidue,
    Sellmeier,
)

__all__ = [
    "AutoFDTDValidationWarning",
    "AutoFDTDModel",
    "AbstractSubpixelPolicy",
    "AutoGrid",
    "Box",
    "ClipOperation",
    "CustomGrid",
    "CustomGridBoundaries",
    "Cylinder",
    "Debye",
    "Drude",
    "GeometryArray",
    "GeometryGroup",
    "GeometryTransform",
    "GridRefinement",
    "GridSpec",
    "LayerRefinementSpec",
    "Lorentz",
    "Medium",
    "PECMedium",
    "PMCMedium",
    "PoleResidue",
    "Sellmeier",
    "PolarizedAveraging",
    "PolySlab",
    "PrimitiveGeometry",
    "ResolvedGrid",
    "ResolvedGridAxis",
    "Scene",
    "Simulation",
    "Sphere",
    "Structure",
    "StructurePrecedence",
    "StructurePriorityMode",
    "Staircasing",
    "SubpixelSpec",
    "TaggedModel",
    "Transformed",
    "UniformGrid",
    "UnsupportedFeatureError",
]
