"""AutoFDTD package scaffold for Phase 1 Maxwell solver work."""

from autofdtd.api import (
    Box,
    Cylinder,
    Debye,
    Drude,
    GeometryTransform,
    Lorentz,
    Medium,
    PECMedium,
    PMCMedium,
    PolarizedAveraging,
    PoleResidue,
    PolySlab,
    PrimitiveGeometry,
    Scene,
    Sellmeier,
    Simulation,
    Sphere,
    Staircasing,
    Structure,
    StructurePriorityMode,
    SubpixelSpec,
)
from autofdtd.core import AutoFDTDModel, TaggedModel
from autofdtd.ir import (
    EXECUTION_PACKAGE_FORMAT,
    IR_SCHEMA_VERSION,
    ExecutionPackageIR,
    execution_package_json_schema,
    simulation_to_ir,
)
from autofdtd.planning import (
    FeatureEntry,
    FeatureStatus,
    NamespacePlan,
    feature_entry,
    feature_matrix,
    feature_status,
    planned_namespace_map,
)
from autofdtd.version import __version__

__all__ = [
    "FeatureEntry",
    "FeatureStatus",
    "NamespacePlan",
    "AutoFDTDModel",
    "Box",
    "Cylinder",
    "Debye",
    "Drude",
    "EXECUTION_PACKAGE_FORMAT",
    "ExecutionPackageIR",
    "GeometryTransform",
    "Lorentz",
    "Medium",
    "PECMedium",
    "PMCMedium",
    "PoleResidue",
    "Sellmeier",
    "IR_SCHEMA_VERSION",
    "PolarizedAveraging",
    "PolySlab",
    "PrimitiveGeometry",
    "Scene",
    "Simulation",
    "Sphere",
    "Staircasing",
    "Structure",
    "StructurePriorityMode",
    "SubpixelSpec",
    "TaggedModel",
    "__version__",
    "feature_entry",
    "execution_package_json_schema",
    "feature_matrix",
    "feature_status",
    "planned_namespace_map",
    "simulation_to_ir",
]
