#!/bin/bash

# Ralph Loop Runner: autofdtd Bug Fix Campaign
# Generated by chief-wiggum
#
# This script orchestrates Claude Code to process tasks one at a time.
# Each iteration runs in a fresh context window.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SPEC_FILE="${SCRIPT_DIR}/spec.md"
PROMPT_FILE="${SCRIPT_DIR}/prompt.md"
LOG_FILE="${SCRIPT_DIR}/ralph.log"


# Check required files exist
if [[ ! -f "$SPEC_FILE" ]]; then
    echo "Error: $SPEC_FILE not found"
    exit 1
fi

if [[ ! -f "$PROMPT_FILE" ]]; then
    echo "Error: $PROMPT_FILE not found"
    exit 1
fi

# Display warning and require acknowledgment
echo ""
echo "┌─────────────────────────────────────────────────────────────────────────────┐"
echo "│  WARNING: This script uses --dangerously-skip-permissions                  │"
echo "├─────────────────────────────────────────────────────────────────────────────┤"
echo "│  Claude Code will execute tools (file writes, bash commands, etc.)          │"
echo "│  WITHOUT asking for permission. This means:                                 │"
echo "│                                                                             │"
echo "│  - Claude will execute whatever the prompt and spec instruct                │"
echo "│  - There is no confirmation before destructive actions                      │"
echo "│  - YOU are responsible for reviewing tasks before running                   │"
echo "│                                                                             │"
echo "│  Before continuing, ensure you have reviewed:                               │"
echo "│    - $SPEC_FILE (the tasks Claude will execute)                             │"
echo "│    - $PROMPT_FILE (the instructions Claude will follow)                     │"
echo "└─────────────────────────────────────────────────────────────────────────────┘"
echo ""

read -p "Do you acknowledge this and want to proceed? [y/N] " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo ""

# Count pending tasks
count_pending() {
    local count
    count=$(grep -c "PENDING:" "$SPEC_FILE" 2>/dev/null) || count=0
    echo "$count"
}

# Stream filter: reads stream-json from stdin, logs raw JSON to file,
# prints human-readable status to terminal.
# Usage: claude ... | stream_filter <log_file>
stream_filter() {
    python3 -u -c '
import json, sys

log_file = sys.argv[1]

def fmt(name, inp):
    n = name.lower()
    if n == "read":
        return "Reading " + inp.get("file_path", "")
    elif n == "edit":
        return "Editing " + inp.get("file_path", "")
    elif n == "write":
        return "Writing " + inp.get("file_path", "")
    elif n == "bash":
        cmd = inp.get("command", "")
        return "Running: " + (cmd[:97] + "..." if len(cmd) > 100 else cmd)
    elif n == "glob":
        pat = inp.get("pattern", "")
        path = inp.get("path", "")
        return "Searching for " + pat + (" in " + path if path else "")
    elif n == "grep":
        pat = inp.get("pattern", "")
        path = inp.get("path", "")
        return "Searching for " + pat + (" in " + path if path else "")
    elif n == "task":
        desc = inp.get("description", inp.get("prompt", ""))[:80]
        return "Spawning agent: " + desc
    elif n.startswith("mcp__"):
        short = n.replace("mcp__", "").replace("plugin_meta_mux__", "")
        return "Calling " + short
    else:
        return "Using " + name

for line in sys.stdin:
    with open(log_file, "a") as f:
        f.write(line)
    line = line.strip()
    if not line:
        continue
    try:
        d = json.loads(line)
    except (json.JSONDecodeError, ValueError):
        continue
    t = d.get("type", "")
    if t == "assistant":
        for item in d.get("message", {}).get("content", []):
            it = item.get("type", "")
            if it == "tool_use":
                print(fmt(item.get("name", "?"), item.get("input", {})), flush=True)
            elif it == "text":
                text = item.get("text", "").strip()
                if text:
                    print(text, flush=True)
    elif t == "result":
        dur = d.get("duration_ms", 0) / 1000
        err = d.get("is_error", False)
        status = "Error" if err else "Done"
        print(status + " ({:.0f}s)".format(dur), flush=True)
' "$1"
}

# Main loop
SEPARATOR="──────────────────────────────────────────────────────────────────────────────"
ITERATION=0

echo "" | tee -a "$LOG_FILE"
echo "$SEPARATOR" | tee -a "$LOG_FILE"
echo "  autofdtd bug fix loop started at $(date)" | tee -a "$LOG_FILE"
echo "$SEPARATOR" | tee -a "$LOG_FILE"

while true; do
    pending=$(count_pending)

    if [[ "$pending" -eq 0 ]]; then
        echo "" | tee -a "$LOG_FILE"
        echo "$SEPARATOR" | tee -a "$LOG_FILE"
        echo "  All tasks complete!" | tee -a "$LOG_FILE"
        echo "$SEPARATOR" | tee -a "$LOG_FILE"
        break
    fi

    ITERATION=$((ITERATION + 1))
    echo "" | tee -a "$LOG_FILE"
    echo "$SEPARATOR" | tee -a "$LOG_FILE"
    echo "  Iteration $ITERATION  |  $pending pending  |  $(date)" | tee -a "$LOG_FILE"
    echo "$SEPARATOR" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"

    # Run Claude Code with the prompt
    # --dangerously-skip-permissions is required for non-interactive execution
    # --output-format stream-json --verbose enables real-time streaming
    # cd to autofdtd root (parent of phase2.5/) so Claude works in the right directory
    cd "${SCRIPT_DIR}/.." && claude --dangerously-skip-permissions \
        --output-format stream-json \
        --verbose \
        -p "$(cat "$PROMPT_FILE")" 2>&1 | stream_filter "$LOG_FILE"

    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        echo "" | tee -a "$LOG_FILE"
        echo "$SEPARATOR" | tee -a "$LOG_FILE"
        echo "  Error: Claude exited with non-zero status" | tee -a "$LOG_FILE"
        echo "  Pausing for manual intervention. Fix the issue and re-run this script." | tee -a "$LOG_FILE"
        echo "$SEPARATOR" | tee -a "$LOG_FILE"
        exit 1
    fi

    # Brief pause between iterations
    sleep 2
done

echo "" | tee -a "$LOG_FILE"
echo "Ralph loop finished at $(date)" | tee -a "$LOG_FILE"
